server:
  port: 8081

spring:
  application:
    name: Eureka-Server-2


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000
